<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findProducerByName($username) {
        $producers = $this->getEntityManager()->createQuery(
                'Select u FROM AppBundle:User u WHERE u.username LIKE :username')
                ->setParameter('username', '%'.$username.'%')
                ->getResult();
        return $producers;
    }
}
