<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function findAllWineProducers() {
        $producers = $this->getEntityManager()->createQuery(
                'Select u FROM AppBundle:User u ORDER BY u.name ASC WHERE u.wina NOT NULL')
                ->getResult();
        return $producers;
    }
}
