<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * WinoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WinoRepository extends EntityRepository
{
    public function findWineByNazwa($nazwa) {
        $wina = $this->getEntityManager()->createQuery(
                'SELECT w FROM AppBundle:Wino w WHERE w.nazwa LIKE :nazwa')
                ->setParameter("nazwa", '%'.$nazwa.'%')
                ->getResult();
        return $wina;
    }
}
